### ISSUE TITLE
final günü paylaşmadaki amaç

### ISSUE THREAD

**Issue by frknbasaran** [co3moz/veri-iletisimi#1]
merhaba

ben bu dersi almıyorum ama alan tanıdıklarım var, bu kadar güzel hazırlanmış bir kaynağı bizimle paylaştığınız için öncelikle teşekkür ederim. 

ancak; siz nasıl bir yavşak nasıl bir ibne nasıl bir çancı pezevenksiniz ki bunları sınav günü paylaşıyorsunuz sayın amınakoduğum.

best regards.
Furkan Başaran
National Aeronautics and Space Administration
Houston / USA

**Comment by frknbasaran** [comment]
Argo ifadelerim için özür dilerim.

**Comment by co3moz** [comment]
Yazmaya başlayalı 10 saat oldu sayın zeki bey. Ancak bitirebildim :facepunch:

**Comment by frknbasaran** [comment]
o eli indir :santa:

**Comment by co3moz** [comment]
Yürek yemiş gelmiş :heart:

**Comment by gokselpirnal** [comment]
doğan biz ne yicez

2016-01-05 11:45 GMT+02:00 Doğan Derya notifications@github.com:

**Comment by frknbasaran** [comment]
pizza söyleyin :pizza:

**Comment by co3moz** [comment]
Ne bilim ama ben bir 1 saat uyuyam ya pencerelerim kapanıyor :cry:
